/* Generated By:JavaCC: Do not edit this line. MyNewGrammarConstants.java */
package Package;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyNewGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int MULTIPLY = 7;
  /** RegularExpression Id. */
  int LP = 8;
  /** RegularExpression Id. */
  int RP = 9;
  /** RegularExpression Id. */
  int NUM = 10;
  /** RegularExpression Id. */
  int FACTOR = 11;
  /** RegularExpression Id. */
  int EXPONENT = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "<MULTIPLY>",
    "\"(\"",
    "\")\"",
    "<NUM>",
    "\"!\"",
    "\"^\"",
    "\";\"",
  };

}
